"""Added samples table

Revision ID: 1d2a33105cbf
Revises: c34db6c8476d
Create Date: 2021-06-29 10:03:11.982575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2a33105cbf'
down_revision = 'c34db6c8476d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('sample_type', sa.Enum('whole_blood', 'plasma', 'cf_dna', name='sampletype'), nullable=False),
    sa.Column('accession_date', sa.DateTime(), nullable=False),
    sa.Column('store_date', sa.DateTime(), nullable=True),
    sa.Column('thaw_count', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    # ### end Alembic commands ###
