"""Trying racks and rack positions.

Revision ID: 1f01c8bae22d
Revises: 8dfc595df6f3
Create Date: 2021-07-05 17:22:39.621532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f01c8bae22d'
down_revision = '8dfc595df6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freezer_id', sa.Integer(), nullable=True),
    sa.Column('open_position', sa.Integer(), nullable=False),
    sa.Column('max_position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_position', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack_positions')
    op.drop_table('racks')
    # ### end Alembic commands ###
