"""Removed open positions db entry for freezer due to change in functionality.

Revision ID: 67450e57840c
Revises: 1c3def6d8234
Create Date: 2021-07-22 11:16:33.439605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67450e57840c'
down_revision = '1c3def6d8234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freezers', 'open_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freezers', sa.Column('open_position', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
