"""More typos

Revision ID: 73b3ceb08691
Revises: e1c8ccb09dcc
Create Date: 2021-07-05 17:31:49.614149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b3ceb08691'
down_revision = 'e1c8ccb09dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'rack_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('rack_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
