"""Removing unnecessary field

Revision ID: 8dfc595df6f3
Revises: f22fc8d2f2b0
Create Date: 2021-07-02 18:44:19.905706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfc595df6f3'
down_revision = 'f22fc8d2f2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'stored')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('stored', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
