"""Removed unnecessary column from plate, open_well.

Revision ID: 92e9847f9844
Revises: ced7bb15dfbb
Create Date: 2021-07-16 11:12:56.778883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e9847f9844'
down_revision = 'ced7bb15dfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plates', 'open_well')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plates', sa.Column('open_well', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
