"""Adding freezers to the database

Revision ID: ced7bb15dfbb
Revises: 7cc6649a7162
Create Date: 2021-07-07 10:14:05.343087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced7bb15dfbb'
down_revision = '7cc6649a7162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freezers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_position', sa.Integer(), nullable=False),
    sa.Column('max_position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freezer_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freezer_position', sa.Integer(), nullable=False),
    sa.Column('freezer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['freezer_id'], ['freezers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('plates_rack_position_id_fkey', 'plates', type_='foreignkey')
    op.create_foreign_key(None, 'plates', 'rack_positions', ['rack_position_id'], ['id'])
    op.add_column('racks', sa.Column('freezer_position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'racks', 'freezer_positions', ['freezer_position_id'], ['id'])
    op.drop_column('racks', 'freezer_id')
    op.drop_constraint('samples_well_id_fkey', 'samples', type_='foreignkey')
    op.create_foreign_key(None, 'samples', 'wells', ['well_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.create_foreign_key('samples_well_id_fkey', 'samples', 'wells', ['well_id'], ['id'], ondelete='CASCADE')
    op.add_column('racks', sa.Column('freezer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'racks', type_='foreignkey')
    op.drop_column('racks', 'freezer_position_id')
    op.drop_constraint(None, 'plates', type_='foreignkey')
    op.create_foreign_key('plates_rack_position_id_fkey', 'plates', 'rack_positions', ['rack_position_id'], ['id'], ondelete='CASCADE')
    op.drop_table('freezer_positions')
    op.drop_table('freezers')
    # ### end Alembic commands ###
