"""new column for manifests for samples

Revision ID: e001cf023a38
Revises: 67450e57840c
Create Date: 2021-08-10 01:39:49.828814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e001cf023a38'
down_revision = '67450e57840c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('manifest_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'manifest_url')
    # ### end Alembic commands ###
