"""Adding wells and plates.

Revision ID: f22fc8d2f2b0
Revises: 1d2a33105cbf
Create Date: 2021-07-02 17:51:50.187238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22fc8d2f2b0'
down_revision = '1d2a33105cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('thaw_count', sa.Integer(), nullable=False),
    sa.Column('store_date', sa.DateTime(), nullable=True),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('open_well', sa.Integer(), nullable=False),
    sa.Column('max_well', sa.Integer(), nullable=False),
    sa.Column('stored', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_position', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('samples', sa.Column('well_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'samples', 'wells', ['well_id'], ['id'], ondelete='CASCADE')
    op.drop_column('samples', 'box_id')
    op.drop_column('samples', 'plate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('plate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('samples', sa.Column('box_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'well_id')
    op.drop_table('wells')
    op.drop_table('plates')
    # ### end Alembic commands ###
